### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#105]
Version 2.0 is almost ready to release.
This issue will be used for tracking blockers and last things to finish.
Current list of things to do:

- [x] Document creation of templates
- [x] Wait for Traefik 1.5 release
- [x] [Rebuild docker-compose projects on re-deployment](https://github.com/exoframejs/exoframe/issues/108)
- [x] [Allow use with existing traefik container](https://github.com/exoframejs/exoframe/issues/103)
- [x] [Allow specifying traefik image name and additional run params](https://github.com/exoframejs/exoframe/issues/107)
- [x] Document 3rd party template usage and management
- [x] Make exoframe-cli tests more reliable

**Comment by yamalight** [comment]
Good way to make sure tests work reliably is to run them via [travis-ci docker images](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image)

**Comment by yamalight** [comment]
We are green to release as soon as fastify 1.0 and traefik 1.5 are released.

**Comment by yamalight** [comment]
We might opt in to release 2.0 once traefik 1.5 is out since fastify guys don't have ETA for 1.0 (it also work perfectly fine with current version). 
Later fastify can be updated to 1.0 via patch.

**Comment by yamalight** [comment]
Traefik 1.5 is released. I'm planning to release Exoframe 2.0 today, server will come with latest fastify version and will later be updated to fastify 1.0

**Comment by yamalight** [comment]
And Exoframe 2.0 is out.
