### ISSUE TITLE
Beta checklist

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#17]
Before beta release, we need the following things:
- [x] make sure all [bugs](https://github.com/exoframejs/exoframe/issues?q=is%3Aissue+is%3Aopen+label%3Abug) are fixed
- [x] make sure all new [minor features](https://github.com/exoframejs/exoframe/issues?q=is%3Aissue+is%3Aopen+label%3A%22minor+feature%22) are implemented
- [x] unit tests to make sure everything works:
  - [x] unit tests for server
  - [x] unit tests for cli
- [x] setup CI/CD to auto-test and auto-publish new versions
- [ ] refactor and cleanup code (after unit tests are done)
- [ ] implement all the major features
- [ ] update docs to reflect current state of tool
