### ISSUE TITLE
Release v5.1

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#247]
Release v5.1 that will include following features:

- [x] Allow removing deployments using token (https://github.com/exoframejs/exoframe/pull/246)
- [x] Remove deployments by url (https://github.com/exoframejs/exoframe-server/pull/24)
- [x] Allow non-interactive config updates (https://github.com/exoframejs/exoframe/issues/218)
- [x] Allow for alternative config file to be used (#215)
- [x] Noninteractive secret creation (https://github.com/exoframejs/exoframe/issues/232)
- [x] Function config should not ask for irrelevant values (#242)
- [x] Add test for function config generation (#249)

**Comment by SeaLife** [comment]
Can feature 1-3 get a pre-release, so i can use this on a real CI environment?
After #248 is merged. :)

**Comment by yamalight** [comment]
Sure! Server should already be available under `exoframe/server:develop`. 
For the cli I'd need to bump an npm version for pre-release - will do in a minute.

**Comment by yamalight** [comment]
@SeaLife `5.0.2-dev` is now up on npm for testing!

**Comment by SeaLife** [comment]
This seems to be working fine, there are some issues with the pipeline but they are related to an issue in Gitlab itself. :)

Would like to see a github release for this. (wrote a little script to fetch the exoframe client from github, cause its faster and i can cache it easily)

```
    - export PATH="$(pwd)/.cache:$PATH"
    - if [ ! -d .cache ]; then mkdir .cache; fi
    - if [ ! -f ".cache/exoframe-${EXOFRAME_VERSION}" ]; then wget -q -O ".cache/exoframe-${EXOFRAME_VERSION}" https://github.com/exoframejs/exoframe/releases/download/${EXOFRAME_VERSION}/exoframe-linux && chmod +x ".cache/exoframe-${EXOFRAME_VERSION}"; fi
    - ln -s "exoframe-${EXOFRAME_VERSION}" .cache/exoframe
```

**Comment by yamalight** [comment]
@SeaLife sweet! 
I'm planning to release v5.1 early next week with all this goodness, maybe even Monday if everything goes as planned 🤔

**Comment by SeaLife** [comment]
Okay nice! Nice tooling, found this in reddit.com/r/selfhosted :)
Keep up the good work, will probably do more for this project :D

**Comment by yamalight** [comment]
And v5.1 is up on CI for release. Once the builds are done - it should be up on NPM. Closing this.
